local Runtime = _G["MidnightCooldownManager"]
if not Runtime then return end
local ns = Runtime._OptionsNS
local CDM = Runtime

ns.ConfigKeys = {
    order = {
        "cooldowngroups",
        "styling",
        "text",
        "bars",
        "racials",
        "defensives",
        "trinkets",
        "externals",
        "resources",
        "glow",
        "fading",
        "assist",
        "positions",
        "buffgroups",
    },
    categories = {
        cooldowngroups = {
            label = "Cooldown Groups",
            keys = {
                "cooldownGroups",
                "ungroupedCooldownOverrides",
                "sizeEssRow1",
                "sizeEssRow2",
                "sizeUtility",
                "sizeBuff",
                "spacing",
                "maxRowEss",
                "utilityWrap",
                "maxRowUtil",
                "utilityUnlock",
                "utilityXOffset",
                "utilityVertical",
            },
        },
        styling = {
            label = "Border & Visual Styling",
            keys = {
                "borderFile",
                "borderSize",
                "borderOffsetX",
                "borderOffsetY",
                "borderColor",
                "zoomIcons",
                "zoomAmount",
                "hideIconOverlay",
                "hideIconOverlayTexture",
                "hideDebuffBorder",
                "hidePandemicIndicator",
                "hideCooldownBling",
                "pandemicCustomizationEnabled",
                "pandemicBorderEnabled",
                "pandemicBorderColorBuffBars",
                "pandemicBorderColor",
                "chargeShowEdge",
                "chargeHideSwipe",
                "chargeHideRechargeTimer",
                "swipeColor",
                "hideGCDSwipe",
                "hideBuffSwipe",
                "disableCooldownDesat",
                "cooldownIconTintEnabled",
                "buffIconTintEnabled",
                "cooldownIconTintColor",
            },
        },
        text = {
            label = "Text & Font Settings",
            keys = {
                "textFont",
                "textFontOutline",
                "cooldownFontSize",
                "cooldownColor",
                "cooldownDecimalThreshold",
                "cooldownColorThresholdEnabled",
                "cooldownColorThreshold",
                "cooldownColorThresholdColor",
                "essRow2CooldownFontSize",
                "utilityCooldownFontSize",
                "chargeFontSize",
                "utilityChargeFontSize",
                "chargeColor",
                "chargePosition",
                "chargeOffsetX",
                "chargeOffsetY",
                "essRow2ChargeFontSize",
                "essRow2ChargeColor",
                "essRow2ChargePosition",
                "essRow2ChargeOffsetX",
                "essRow2ChargeOffsetY",
                "utilityChargeColor",
                "utilityChargePosition",
                "utilityChargeOffsetX",
                "utilityChargeOffsetY",
                "countFontSize",
                "countColor",
                "buffCooldownFontSize",
                "buffCooldownColor",
                "countPositionMain",
                "countOffsetXMain",
                "countOffsetYMain",
                "buffBarNameFontSize",
                "buffBarNameColor",
                "buffBarNameOffsetX",
                "buffBarNameOffsetY",
                "buffBarDurationFontSize",
                "buffBarDurationColor",
                "buffBarDurationPosition",
                "buffBarDurationOffsetX",
                "buffBarDurationOffsetY",
            },
        },
        bars = {
            label = "Buff Bar Settings",
            keys = {
                "buffBarWidth",
                "buffBarHeight",
                "buffBarSpacing",
                "buffBarGrowDirection",
                "buffBarIconPosition",
                "buffBarIconGap",
                "buffBarShowName",
                "buffBarNameMaxChars",
                "buffBarShowDuration",
                "buffBarShowApplications",
                "buffBarApplicationsFontSize",
                "buffBarApplicationsColor",
                "buffBarApplicationsPosition",
                "buffBarApplicationsOffsetX",
                "buffBarApplicationsOffsetY",
                "buffBarTexture",
                "buffBarColor",
                "buffBarBackgroundColor",
                "buffBarFillDirection",
                "barGroups",
                "ungroupedBarOverrides",
            },
        },
        racials = {
            label = "Racials Tracker Settings",
            keys = {
                "racialsEnabled",
                "racialsIconWidth",
                "racialsIconHeight",
                "racialsAnchorPoint",
                "racialsOffsetX",
                "racialsOffsetY",
                "racialsChargeFontSize",
                "racialsCooldownFontSize",
                "racialsChargePosition",
                "racialsChargeOffsetX",
                "racialsChargeOffsetY",
                "racialsUsePartyFrame",
                "racialsPartyFrameSide",
                "racialsPartyFrameOffsetX",
                "racialsPartyFrameOffsetY",
                "racialsRaidFrameAnchorPoint",
                "racialsRaidFrameRelativePoint",
                "racialsRaidFrameOffsetX",
                "racialsRaidFrameOffsetY",
                "racialsChargeColor",
                "racialsShowItemsAtZeroStacks",
                "racialsCustomEntries",
                "racialsOrderPerSpec",
                "racialsDisabled",
            },
        },
        defensives = {
            label = "Defensives Tracker Settings",
            keys = {
                "defensivesEnabled",
                "defensivesIconWidth",
                "defensivesIconHeight",
                "defensivesAnchorPoint",
                "defensivesOffsetX",
                "defensivesOffsetY",
                "defensivesChargeFontSize",
                "defensivesCooldownFontSize",
                "defensivesChargePosition",
                "defensivesChargeOffsetX",
                "defensivesChargeOffsetY",
                "defensivesDisabledSpells",
                "defensivesCustomSpells",
                "defensivesOrder",
            },
        },
        trinkets = {
            label = "Trinkets Tracker Settings",
            keys = {
                "trinketsEnabled",
                "trinketsIconWidth",
                "trinketsIconHeight",
                "trinketsAnchorPoint",
                "trinketsOffsetX",
                "trinketsOffsetY",
                "trinketsCooldownFontSize",
                "trinketsShowPassive",
                "trinketsBlacklist",
                "trinketsMode",
                "trinketsEssentialRow",
                "trinketsEssentialPosition",
            },
        },
        externals = {
            label = "Externals Tracker Settings",
            keys = {
                "externalsEnabled",
                "externalsIconWidth",
                "externalsIconHeight",
                "externalsCooldownFontSize",
                "externalsDisableBlink",
            },
        },
        resources = {
            label = "Class Resources",
            keys = {
                "resourceClassEnabled",
                "resourceWidth",
                "resourceHeight",
                "resourceGap",
                "resourceTickWidth",
                "resourceOutline",
                "resourceAnchorTarget",
                "resourceAnchorPoint",
                "resourceRelativePoint",
                "resourceOffsetX",
                "resourceOffsetY",
                "resourceTexture",
                "resourceBgTexture",
                "resourceBackgroundColor",
                "resourceColorOverrides",
                "resourceShowText",
                "resourceTextSize",
                "resourceRuneTextSize",
                "resourceRuneShowTime",
                "resourceFilledAlpha",
                "resourceEmptyAlpha",
                "resourceFillReverse",
                "resourceHideOOC",
                "resourceHideWhenFull",
                "resourceHideWhenEmpty",
                "resourceLoadHideMounted",
                "resourceLoadHideInVehicle",
                "resourceLoadHideResting",
                "resourceLoadHideInCombat",
                "resourceLoadHideOutOfCombat",
                "resourceLoadHideStealthed",
                "resourceLoadHideSolo",
                "resourceLoadHideInGroup",
                "resourceLoadHideInInstance",
                "resourceLoadHideNoTarget",
                "resourceLoadHideHasTarget",
                "resourceLoadHideNoHostileTarget",
                "resourceLoadHideNoFriendlyTarget",
                "resourceShowStagger",
                "resourceShowEbonMight",
                "resourceShowEleMaelstrom",
                "resourceShowShadowInsanity",
                "resourceShowChargedComboPoints",
                "resourcePowerBarEnabled",
                "resourcePowerBarWidth",
                "resourcePowerBarHeight",
                "resourcePowerBarAnchorTarget",
                "resourcePowerBarAnchorPoint",
                "resourcePowerBarRelativePoint",
                "resourcePowerBarOffsetX",
                "resourcePowerBarOffsetY",
                "resourcePowerBarTexture",
                "resourcePowerBarBgTexture",
                "resourcePowerBarOutline",
                "resourcePowerBarBackgroundColor",
                "resourcePowerBarColorOverrides",
                "resourcePowerBarTextMode",
                "resourcePowerBarTextSize",
                "resourcePowerBarSmooth",
                "resourcePowerBarLoadHideMounted",
                "resourcePowerBarLoadHideInVehicle",
                "resourcePowerBarLoadHideResting",
                "resourcePowerBarLoadHideInCombat",
                "resourcePowerBarLoadHideOutOfCombat",
                "resourcePowerBarLoadHideStealthed",
                "resourcePowerBarLoadHideSolo",
                "resourcePowerBarLoadHideInGroup",
                "resourcePowerBarLoadHideInInstance",
                "resourcePowerBarLoadHideNoTarget",
                "resourcePowerBarLoadHideHasTarget",
                "resourcePowerBarLoadHideNoHostileTarget",
                "resourcePowerBarLoadHideNoFriendlyTarget",
                "resourceHPBarEnabled",
                "resourceHPBarWidth",
                "resourceHPBarHeight",
                "resourceHPBarAnchorTarget",
                "resourceHPBarAnchorPoint",
                "resourceHPBarRelativePoint",
                "resourceHPBarOffsetX",
                "resourceHPBarOffsetY",
                "resourceHPBarTexture",
                "resourceHPBarBgTexture",
                "resourceHPBarOutline",
                "resourceHPBarBackgroundColor",
                "resourceHPBarColorMode",
                "resourceHPBarColor",
                "resourceHPBarGlobalColor",
                "resourceHPBarDarkColor",
                "resourceHPBarGradientLow",
                "resourceHPBarGradientMid",
                "resourceHPBarGradientHigh",
                "resourceHPBarTextMode",
                "resourceHPBarTextSize",
                "resourceHPBarLoadHideMounted",
                "resourceHPBarLoadHideInVehicle",
                "resourceHPBarLoadHideResting",
                "resourceHPBarLoadHideInCombat",
                "resourceHPBarLoadHideOutOfCombat",
                "resourceHPBarLoadHideStealthed",
                "resourceHPBarLoadHideSolo",
                "resourceHPBarLoadHideInGroup",
                "resourceHPBarLoadHideInInstance",
                "resourceHPBarLoadHideNoTarget",
                "resourceHPBarLoadHideHasTarget",
                "resourceHPBarLoadHideNoHostileTarget",
                "resourceHPBarLoadHideNoFriendlyTarget",
            },
        },
        glow = {
            label = "Glow Settings",
            keys = {
                "glowType",
                "glowUseCustomColor",
                "glowColor",
                "glowPixelLines",
                "glowPixelFrequency",
                "glowPixelLength",
                "glowPixelThickness",
                "glowPixelXOffset",
                "glowPixelYOffset",
                "glowPixelBorder",
                "glowAutocastParticles",
                "glowAutocastFrequency",
                "glowAutocastScale",
                "glowAutocastXOffset",
                "glowAutocastYOffset",
                "glowButtonFrequency",
                "glowProcDuration",
                "glowProcXOffset",
                "glowProcYOffset",
            },
        },
        assist = {
            label = "Assist Settings",
            keys = {
                "rotationAssistEnabled",
                "rotationAssistGlowRatio",
                "assistEnabled",
                "assistFontSize",
                "assistColor",
                "assistPosition",
                "assistOffsetX",
                "assistOffsetY",
                "pressOverlayEnabled",
                "pressOverlayTint",
                "pressOverlayTintColor",
                "pressOverlayHighlight",
                "pressOverlayBorder",
                "pressOverlayBorderColor",
            },
        },
        fading = {
            label = "Fading Settings",
            keys = {
                "fadingEnabled",
                "fadingTriggerNoTarget",
                "fadingTriggerOOC",
                "fadingTriggerMounted",
                "fadingOpacity",
                "fadingEssential",
                "fadingUtility",
                "fadingBuffs",
                "fadingBuffBars",
                "fadingRacials",
                "fadingDefensives",
                "fadingTrinkets",
            },
        },
        positions = {
            label = "Positions & Locking",
            keys = {
                "editModePositions",
                "utilityYOffset",
            },
        },
        buffgroups = {
            label = "Buff Groups",
            keys = {
                "buffGroups",
                "ungroupedBuffOverrides",
                "spellRegistry",
                "customBuffRegistry",
                "ungroupedCustomBuffOrder",
            },
        },
    },
}

do
    local defaults = CDM.defaults
    if not defaults then return end

    local keysInCategories = {}
    for catName, catDef in pairs(ns.ConfigKeys.categories) do
        for _, key in ipairs(catDef.keys) do
            if keysInCategories[key] then
                print("|cffff6600[MCDM] ConfigKeys: '" .. key .. "' in both '" .. keysInCategories[key] .. "' and '" .. catName .. "'|r")
            end
            keysInCategories[key] = catName
        end
    end

    for key in pairs(defaults) do
        if not keysInCategories[key] then
            print("|cffff6600[MCDM] ConfigKeys: default key '" .. key .. "' not in any export category|r")
        end
    end

    for key, catName in pairs(keysInCategories) do
        if defaults[key] == nil then
            print("|cffff6600[MCDM] ConfigKeys: export key '" .. key .. "' (in '" .. catName .. "') has no default|r")
        end
    end
end
