local AddonName = "MidnightCooldownManager"
local CDM = _G[AddonName]

CDM.defaults = {
    sizeEssRow1 = { w = 46, h = 40 },
    sizeEssRow2 = { w = 46, h = 40 },
    sizeUtility = { w = 46, h = 40 },
    sizeBuff = { w = 40, h = 36 },
    spacing = 1,
    maxRowEss = 9,
    utilityYOffset = 0,
    utilityWrap = false,
    maxRowUtil = 8,
    utilityUnlock = false,
    utilityXOffset = 0,
    utilityVertical = false,

    -- BuffBar viewer settings
    buffBarWidth = 0,               -- 0 = auto (match Essential row 1 width)
    buffBarHeight = 20,
    buffBarSpacing = 1,
    buffBarGrowDirection = "DOWN",   -- "UP" or "DOWN"
    buffBarIconPosition = "LEFT",   -- "LEFT", "RIGHT", "HIDDEN"
    buffBarIconGap = 1,             -- Gap between icon and bar
    buffBarShowName = true,
    buffBarNameMaxChars = 0,
    buffBarShowDuration = true,
    buffBarTexture = "Solid",
    buffBarColor = { r = 0.4, g = 0.6, b = 0.9, a = 1 },
    buffBarBackgroundColor = { r = 0.1, g = 0.1, b = 0.1, a = 0.8 },
    buffBarFillDirection = "RIGHT_TO_LEFT",
    buffBarNameFontSize = 15,
    buffBarNameColor = { r = 1, g = 1, b = 1, a = 1 },
    buffBarNameOffsetX = 2,
    buffBarNameOffsetY = 0,
    buffBarDurationFontSize = 15,
    buffBarDurationColor = { r = 1, g = 1, b = 1, a = 1 },
    buffBarDurationPosition = "RIGHT",
    buffBarDurationOffsetX = -2,
    buffBarDurationOffsetY = 0,
    buffBarShowApplications = true,
    buffBarApplicationsFontSize = 15,
    buffBarApplicationsColor = { r = 1, g = 1, b = 1, a = 1 },
    buffBarApplicationsPosition = "CENTER",
    buffBarApplicationsOffsetX = 0,
    buffBarApplicationsOffsetY = 0,

    -- Assist
    rotationAssistEnabled = false,
    rotationAssistGlowRatio = 0.33,
    assistEnabled = false,
    assistFontSize = 15,
    assistColor = { r = 1, g = 1, b = 1, a = 1 },
    assistPosition = "TOPRIGHT",
    assistOffsetX = 0,
    assistOffsetY = 0,

    -- Press Overlay
    pressOverlayEnabled = false,
    pressOverlayTint = false,
    pressOverlayTintColor = { r = 1, g = 1, b = 1, a = 0.35 },
    pressOverlayHighlight = true,
    pressOverlayBorder = false,
    pressOverlayBorderColor = { r = 1, g = 1, b = 1, a = 1 },

    -- Module enable/disable toggles
    racialsEnabled = true,
    defensivesEnabled = true,
    trinketsEnabled = true,
    externalsEnabled = true,

    -- Player class resources and auxiliary bars
    resourceClassEnabled = true,
    resourceWidth = 220,
    resourceHeight = 8,
    resourceGap = 1,
    resourceTickWidth = 1,
    resourceOutline = 1,
    resourceAnchorTarget = "essential",
    resourceAnchorPoint = "BOTTOM",
    resourceRelativePoint = "TOP",
    resourceOffsetX = 0,
    resourceOffsetY = 2,
    resourceTexture = "Solid",
    resourceBgTexture = "",
    resourceBackgroundColor = { r = 0, g = 0, b = 0, a = 0.35 },
    resourceColorOverrides = {},
    resourceShowText = false,
    resourceTextSize = 14,
    resourceRuneTextSize = 11,
    resourceRuneShowTime = true,
    resourceFilledAlpha = 1,
    resourceEmptyAlpha = 0.3,
    resourceFillReverse = false,
    resourceHideOOC = false,
    resourceHideWhenFull = false,
    resourceHideWhenEmpty = false,
    resourceLoadHideMounted = false,
    resourceLoadHideInVehicle = false,
    resourceLoadHideResting = false,
    resourceLoadHideInCombat = false,
    resourceLoadHideOutOfCombat = false,
    resourceLoadHideStealthed = false,
    resourceLoadHideSolo = false,
    resourceLoadHideInGroup = false,
    resourceLoadHideInInstance = false,
    resourceLoadHideNoTarget = false,
    resourceLoadHideHasTarget = false,
    resourceLoadHideNoHostileTarget = false,
    resourceLoadHideNoFriendlyTarget = false,
    resourceShowStagger = true,
    resourceShowEbonMight = true,
    resourceShowEleMaelstrom = false,
    resourceShowShadowInsanity = false,
    resourceShowChargedComboPoints = true,

    resourcePowerBarEnabled = true,
    resourcePowerBarWidth = 220,
    resourcePowerBarHeight = 8,
    resourcePowerBarAnchorTarget = "resource",
    resourcePowerBarAnchorPoint = "TOP",
    resourcePowerBarRelativePoint = "BOTTOM",
    resourcePowerBarOffsetX = 0,
    resourcePowerBarOffsetY = -4,
    resourcePowerBarTexture = "Solid",
    resourcePowerBarBgTexture = "",
    resourcePowerBarOutline = 1,
    resourcePowerBarBackgroundColor = { r = 0, g = 0, b = 0, a = 0.35 },
    resourcePowerBarColorOverrides = {},
    resourcePowerBarTextMode = "PERCENT",
    resourcePowerBarTextSize = 13,
    resourcePowerBarSmooth = true,
    resourcePowerBarLoadHideMounted = false,
    resourcePowerBarLoadHideInVehicle = false,
    resourcePowerBarLoadHideResting = false,
    resourcePowerBarLoadHideInCombat = false,
    resourcePowerBarLoadHideOutOfCombat = false,
    resourcePowerBarLoadHideStealthed = false,
    resourcePowerBarLoadHideSolo = false,
    resourcePowerBarLoadHideInGroup = false,
    resourcePowerBarLoadHideInInstance = false,
    resourcePowerBarLoadHideNoTarget = false,
    resourcePowerBarLoadHideHasTarget = false,
    resourcePowerBarLoadHideNoHostileTarget = false,
    resourcePowerBarLoadHideNoFriendlyTarget = false,

    resourceHPBarEnabled = false,
    resourceHPBarWidth = 220,
    resourceHPBarHeight = 6,
    resourceHPBarAnchorTarget = "resource",
    resourceHPBarAnchorPoint = "TOP",
    resourceHPBarRelativePoint = "BOTTOM",
    resourceHPBarOffsetX = 0,
    resourceHPBarOffsetY = -18,
    resourceHPBarTexture = "Solid",
    resourceHPBarBgTexture = "",
    resourceHPBarOutline = 1,
    resourceHPBarBackgroundColor = { r = 0, g = 0, b = 0, a = 0.35 },
    resourceHPBarColorMode = "CLASS",
    resourceHPBarColor = { r = 0.12, g = 0.76, b = 0.28, a = 1 },
    resourceHPBarGlobalColor = { r = 0.12, g = 0.76, b = 0.28, a = 1 },
    resourceHPBarDarkColor = { r = 0.07, g = 0.08, b = 0.09, a = 1 },
    resourceHPBarGradientLow = { r = 0.86, g = 0.16, b = 0.12, a = 1 },
    resourceHPBarGradientMid = { r = 0.95, g = 0.76, b = 0.16, a = 1 },
    resourceHPBarGradientHigh = { r = 0.16, g = 0.78, b = 0.28, a = 1 },
    resourceHPBarTextMode = "PERCENT",
    resourceHPBarTextSize = 13,
    resourceHPBarLoadHideMounted = false,
    resourceHPBarLoadHideInVehicle = false,
    resourceHPBarLoadHideResting = false,
    resourceHPBarLoadHideInCombat = false,
    resourceHPBarLoadHideOutOfCombat = false,
    resourceHPBarLoadHideStealthed = false,
    resourceHPBarLoadHideSolo = false,
    resourceHPBarLoadHideInGroup = false,
    resourceHPBarLoadHideInInstance = false,
    resourceHPBarLoadHideNoTarget = false,
    resourceHPBarLoadHideHasTarget = false,
    resourceHPBarLoadHideNoHostileTarget = false,
    resourceHPBarLoadHideNoFriendlyTarget = false,

    -- Externals (ExternalDefensivesFrame) settings
    externalsIconWidth = 30,
    externalsIconHeight = 30,
    externalsCooldownFontSize = 15,
    externalsDisableBlink = true,

    -- Racials tracker settings
    racialsIconWidth = 40,
    racialsIconHeight = 36,
    racialsAnchorPoint = "BOTTOMLEFT",
    racialsOffsetX = 0,
    racialsOffsetY = 0,
    racialsChargeFontSize = 15,
    racialsChargeColor = { r = 1, g = 1, b = 1, a = 1 },
    racialsCooldownFontSize = 15,
    racialsChargePosition = "BOTTOM",
    racialsChargeOffsetX = 0,
    racialsChargeOffsetY = -2,
    racialsShowItemsAtZeroStacks = false,
    racialsCustomEntries = {},
    racialsOrderPerSpec = {},
    racialsDisabled = {},

    -- Defensives tracker settings
    defensivesIconWidth = 40,
    defensivesIconHeight = 36,
    defensivesAnchorPoint = "TOPRIGHT",
    defensivesOffsetX = 0,
    defensivesOffsetY = 0,
    defensivesChargeFontSize = 15,
    defensivesCooldownFontSize = 15,
    defensivesChargePosition = "TOP",
    defensivesChargeOffsetX = 0,
    defensivesChargeOffsetY = 2,
    defensivesDisabledSpells = {},
    defensivesCustomSpells = {},
    defensivesOrder = {},

    -- Trinkets tracker settings
    trinketsIconWidth = 40,
    trinketsIconHeight = 36,
    trinketsAnchorPoint = "TOPLEFT",
    trinketsOffsetX = 0,
    trinketsOffsetY = 0,
    trinketsCooldownFontSize = 15,
    trinketsShowPassive = true,
    trinketsBlacklist = {},
    trinketsMode = "independent",       -- "independent", "defensives", "essential"
    trinketsEssentialRow = 1,           -- 1 or 2 (which row trinkets appear in)
    trinketsEssentialPosition = "end",  -- "start" or "end"

    -- Party frame anchoring settings
    racialsUsePartyFrame = false,
    racialsPartyFrameSide = "LEFT",
    racialsPartyFrameOffsetX = -1,
    racialsPartyFrameOffsetY = 20,
    racialsRaidFrameAnchorPoint = "BOTTOMLEFT",
    racialsRaidFrameRelativePoint = "TOPLEFT",
    racialsRaidFrameOffsetX = 0,
    racialsRaidFrameOffsetY = 0,

    borderFile = "1 Pixel",
    borderSize = 1,
    borderOffsetX = 0,
    borderOffsetY = 0,
    borderColor = { r = 0, g = 0, b = 0, a = 1 },
    spellRegistry = {},
    editModePositions = {},
    customBuffRegistry = {},
    ungroupedCustomBuffOrder = {},
    buffGroups = {},
    ungroupedBuffPins = {},
    ungroupedBuffOverrides = {},
    barGroups = {},
    ungroupedBarOverrides = {},
    cooldownGroups = {},
    ungroupedCooldownOverrides = {},

    -- Global Text Settings
    textFont = "Friz Quadrata TT",
    textFontOutline = "OUTLINE",

    -- Cooldown Timer Text
    cooldownFontSize = 15,
    essRow2CooldownFontSize = 15,
    utilityCooldownFontSize = 15,
    cooldownColor = { r = 1, g = 1, b = 1, a = 1 },
    cooldownDecimalThreshold = 0,
    cooldownColorThresholdEnabled = false,
    cooldownColorThreshold = 5,
    cooldownColorThresholdColor = { r = 1, g = 0.2, b = 0.2, a = 1 },
    -- ChargeCount
    chargeFontSize = 15,
    utilityChargeFontSize = 15,
    essRow2ChargeFontSize = 15,
    chargeColor = { r = 1, g = 1, b = 1, a = 1 },
    chargePosition = "BOTTOMRIGHT",
    chargeOffsetX = 0,
    chargeOffsetY = 0,
    essRow2ChargeColor = { r = 1, g = 1, b = 1, a = 1 },
    essRow2ChargePosition = "BOTTOMRIGHT",
    essRow2ChargeOffsetX = 0,
    essRow2ChargeOffsetY = 0,
    utilityChargeColor = { r = 1, g = 1, b = 1, a = 1 },
    utilityChargePosition = "BOTTOMRIGHT",
    utilityChargeOffsetX = 0,
    utilityChargeOffsetY = 0,

    -- Applications (buff stacks)
    countFontSize = 15,
    countColor = { r = 1, g = 1, b = 1, a = 1 },

    -- Buff cooldown timer text (applies to all buff containers)
    buffCooldownFontSize = 15,
    buffCooldownColor = { r = 1, g = 1, b = 1, a = 1 },

    -- Main buff stack position
    countPositionMain = "TOP",
    countOffsetXMain = 0,
    countOffsetYMain = 4,

    zoomIcons = true,
    zoomAmount = 0.08,
    hideIconOverlay = true,
    hideIconOverlayTexture = true,
    swipeColor = { r = 0, g = 0, b = 0, a = 0.6 },
    hideGCDSwipe = false,
    hideBuffSwipe = false,
    disableCooldownDesat = false,
    cooldownIconTintEnabled = false,
    buffIconTintEnabled = false,
    cooldownIconTintColor = { r = 0, g = 0, b = 0, a = 1 },

    -- Glow Settings
    glowType = "pixel", -- "pixel", "autocast", "button", "proc"
    glowUseCustomColor = false,
    glowColor = { r = 0.95, g = 0.95, b = 0.32, a = 1 },

    -- Pixel Glow
    glowPixelLines = 8,
    glowPixelFrequency = 0.2,
    glowPixelLength = 0, -- 0 = auto
    glowPixelThickness = 2,
    glowPixelXOffset = 0,
    glowPixelYOffset = 0,
    glowPixelBorder = false,

    -- Autocast Glow
    glowAutocastParticles = 4,
    glowAutocastFrequency = 0.2,
    glowAutocastScale = 1,
    glowAutocastXOffset = 0,
    glowAutocastYOffset = 0,

    -- Button Glow
    glowButtonFrequency = 0, -- 0 = default

    -- Proc Glow
    glowProcDuration = 1,
    glowProcXOffset = 0,
    glowProcYOffset = 0,

    -- Visual elements
    hideDebuffBorder = true,
    hidePandemicIndicator = true,
    hideCooldownBling = true,

    pandemicCustomizationEnabled = false,
    pandemicBorderEnabled = false,
    pandemicBorderColorBuffBars = false,
    pandemicBorderColor   = { r = 1.00, g = 0.70, b = 0.10, a = 1 },

    chargeShowEdge  = false,
    chargeHideSwipe = false,
    chargeHideRechargeTimer = false,

    -- Fading
    fadingEnabled = false,
    fadingTriggerNoTarget = true,
    fadingTriggerOOC = false,
    fadingTriggerMounted = false,
    fadingOpacity = 30,
    fadingEssential = true,
    fadingUtility = true,
    fadingBuffs = true,
    fadingBuffBars = true,
    fadingRacials = true,
    fadingDefensives = true,
    fadingTrinkets = true,
}
